"""
STEP 0 + 1 of the standard EDA method: understand the GRAIN, then PROFILE.

This is the first thing you run on ANY raw dataset, before a single chart.
It answers, for every table:
  - What is one row? (the "grain")
  - What is the key, the date range, the size?
  - For every column: type, % missing, cardinality, example values
  - Airbnb-specific red flags (price stored as text, etc.)

Output: prints a data dictionary to the console AND writes it to
outputs/data_dictionary.md so it becomes a portfolio artifact.

Run:  python 00_profile.py
Needs: pandas, openpyxl  (no plotting libs required)
"""
import sys
import pandas as pd
import config as C

# Windows terminals default to cp1252 and crash on characters like the arrow.
# Force UTF-8 so prints never blow up regardless of console codepage.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 160)


def df_to_markdown(df: pd.DataFrame) -> str:
    """Render a DataFrame as a Markdown table with no extra dependencies
    (pandas' own .to_markdown() requires the 'tabulate' package)."""
    cols = [df.index.name or ""] + [str(c) for c in df.columns]
    rows = ["| " + " | ".join(cols) + " |",
            "| " + " | ".join(["---"] * len(cols)) + " |"]
    for idx, row in df.iterrows():
        cells = [str(idx)] + [str(v) for v in row.tolist()]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def profile_frame(name: str, df: pd.DataFrame, grain: str) -> str:
    """Return a Markdown profile of one dataframe (and print it)."""
    lines = [f"## `{name}` — {grain}", ""]
    lines.append(f"- **{df.shape[0]:,} rows × {df.shape[1]} columns**")
    if "date" in df.columns:
        lines.append(f"- date range: **{df['date'].min()} → {df['date'].max()}**")
    lines.append("")

    prof = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "pct_missing": (df.isna().mean() * 100).round(1),
        "n_unique": df.nunique(),
        "example": [df[c].dropna().iloc[0] if df[c].notna().any() else None
                    for c in df.columns],
    })
    # truncate long example values so the table stays readable
    prof["example"] = prof["example"].astype(str).str.slice(0, 45)

    print(f"\n{'='*70}\n{name}: {grain}")
    print(f"{df.shape[0]:,} rows x {df.shape[1]} cols")
    print(prof.to_string())

    lines.append(df_to_markdown(prof))
    lines.append("")
    return "\n".join(lines)


def main():
    md = ["# Twin Cities Airbnb — Data Dictionary",
          "_Auto-generated by 00_profile.py. This is Step 0-1 of EDA: "
          "know your grain and profile every column before analyzing._", ""]

    # dtype=str on listing_id keeps the huge IDs from being cast to float
    # (the exact bug that corrupted Calendar 2026.csv). Always read IDs as text.
    listings = pd.read_excel(C.LISTINGS_XLSX)
    calendar = pd.read_csv(C.CALENDAR_CSV, parse_dates=["date"],
                           dtype={"listing_id": str})
    reviews  = pd.read_csv(C.REVIEWS_CSV, parse_dates=["date"],
                           dtype={"listing_id": str, "id": str, "reviewer_id": str})

    md.append(profile_frame("listings", listings, "one row = one listing"))
    md.append(profile_frame("calendar", calendar, "one row = one listing-night"))
    md.append(profile_frame("reviews",  reviews,  "one row = one review"))

    # --- Airbnb-specific red-flag checks --------------------------------
    print(f"\n{'='*70}\nRED-FLAG CHECKS")
    flags = ["## Red flags & notes", ""]

    price_sample = listings["price"].dropna().head(3).tolist()
    price_is_text = listings["price"].dtype == object
    print("price dtype:", listings["price"].dtype, "sample:", price_sample)
    if price_is_text:
        flags.append(f"- `price` is TEXT like `{price_sample}` — strip `$`/`,` "
                     "then cast to float (true for the raw .csv export).")
    else:
        flags.append(f"- `price` is already NUMERIC here ({price_sample}) because "
                     "it came from .xlsx. The cleaner handles both cases so the "
                     "same code works on a raw .csv too.")

    # Inside Airbnb already ships estimated occupancy & revenue — big time-saver
    if "estimated_occupancy_l365d" in listings:
        occ = listings["estimated_occupancy_l365d"].describe()[["mean", "50%", "max"]]
        flags.append(f"- `estimated_occupancy_l365d` and `estimated_revenue_l365d` "
                     f"are **already provided** — no need to derive them from the "
                     f"calendar. (occupancy: mean={occ['mean']:.0f}, median={occ['50%']:.0f} nights)")

    # calendar is FORWARD-looking, not history — critical caveat
    flags.append(f"- calendar spans **{calendar['date'].min().date()} → "
                 f"{calendar['date'].max().date()}**: a *forward* snapshot. "
                 "`available='f'` = booked **or** host-blocked, so calendar "
                 "'occupancy' is an UPPER BOUND, not measured demand.")

    # join integrity: do calendar/review listing_ids exist in listings?
    lids = set(listings["id"].astype(str))
    cal_orphans = (~calendar["listing_id"].isin(lids)).mean() * 100
    rev_orphans = (~reviews["listing_id"].isin(lids)).mean() * 100
    flags.append(f"- calendar rows with no matching listing: **{cal_orphans:.1f}%**; "
                 f"reviews with no matching listing: **{rev_orphans:.1f}%** "
                 "(high % means the snapshots are from different dates).")

    for f in flags:
        print(f)
    md.append("\n".join(flags))

    out = C.OUT / "data_dictionary.md"
    out.write_text("\n".join(md), encoding="utf-8")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
